// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LoadDWVentas.Data.Models;

public partial class VwclientesAtendido
{
    public int? EmployeeId { get; set; }

    public string EmployeeName { get; set; }

    public int? Clientes { get; set; }
}