// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LoadDWVentas.Data.Models;

public partial class Vwventa
{
    public string CustomerId { get; set; }

    public string CustomerName { get; set; }

    public int EmployeeId { get; set; }

    public string EmployeeName { get; set; }

    public int ShipperId { get; set; }

    public string CompanyName { get; set; }

    public int? Year { get; set; }

    public int? Month { get; set; }

    public decimal? Total { get; set; }

    public int? Quantity { get; set; }
}